testproject/task/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

urlpatterns = [
  
      path('', views.showlisting, name='showlisting'),
]

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]

testproject/task/models.py
from django.db import models
import os

# Create your models here.

class Sample(models.Model):
    
    User_parent=models.ForeignKey('self', on_delete=models.CASCADE,blank=True,null=True,related_name="owner")
    User_Name=models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    modified_date = models.DateTimeField(auto_now=True,blank=True,null=True)
    def __str__(self):
        
        return self.User_Name
    
    class Meta:
       ordering = ('-created_date',)


class Sample_Files(models.Model):
    Project_Files=models.FileField(upload_to='Project_Files/%Y/%m/%d',blank=True,null=True)
    created_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    modified_date = models.DateTimeField(auto_now=True,blank=True,null=True)
    def __str__(self):
        name , extension = os.path.split(self.Project_Files.name)
        return extension

    def file_size(self):
        value=os.path.getsize(self.Project_Files.path)
        if value < 512000:
            value = value / 1024.0
            ext = 'kb'
        elif value < 4194304000:
            value = value / 1048576.0
            ext = 'mb'
        else:
            value = value / 1073741824.0
            ext = 'gb'
        return '%s %s' % (str(round(value, 2)), ext)
    
    class Meta:
       ordering = ('-created_date',)

testproject/task/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import *
from task.models import *



class Samplefile(ModelForm):
    def __init__(self, *args, **kwargs):
        super(Samplefile, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    
    Project_Files = forms.FileField(required=False,widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Sample_Files
        # exclude=['project','file_uploade_by']
        fields = ('__all__')

testproject/task/views.py
from django.shortcuts import render
from task.models import *
from task.forms import *
from django.http import JsonResponse
from django.core import serializers



def showlisting(request):
    if request.method == 'POST':

        form = Samplefile(data=request.POST, files=request.FILES)
        
        if form.is_valid():
            form.save()
            pdf_data=serializers.serialize("json", Sample_Files.objects.all())
            return JsonResponse(pdf_data,safe=False)

        else:
            print('invalid form')
            

    data=Sample.objects.prefetch_related('owner').filter(User_parent__isnull=True)
    pdf_data=Sample_Files.objects.all()
    return render(request, "frontend/listing.html",{'data':data , 'userform':Samplefile ,'pdf':pdf_data}) 

testproject/templates/frontend/listing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Test Task</title>
</head>
<body>
       
{% if data %}
<h1>Here is Self Refencing Table</h1>
<p>I created a single table Sample with join with itself</p>
{% for parent in data %}
    <h3>{{ parent.User_Name }}</h3>
    {% if parent.owner.count %}
        <ul>
        {% for child in parent.owner.all %}
            <li>{{ child.User_Name }}</li>
                {% if child.owner.count %}
                    <ul>
                    {% for child2 in child.owner.all %}
                        <li>{{ child2.User_Name }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
        {% endfor %}
        </ul>
    {% endif %}
{% endfor %}
{% endif %} 


{% if userform %}
<h1>Add Pdf Using Ajax</h1>
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}

{% for userforms in userform %}
<div class="form-group">
    {{userforms.label}}
    {{userforms}}
</div>
{{userforms.errors}}
{% endfor %}
<input type="button" id="save_pdf" value="Add pdf" class="btn btn-success float-right" "/>
</form>

{% endif %}


{% if pdf %}
<table border="1" id="files_data">
{% for data in pdf %}
<tr><td>File Name</td><td><a href={{data.Project_Files.path}}>{{data.Project_Files}}</a></td></tr>


{% endfor %}
</table>

{% endif %}
</body>
</html>


<head>

</head>










<script>



$(function() {
    $(document).on("click","#save_pdf",function() {
        var data = new FormData($('form').get(0));

        var fileExtension = ['pdf'];
        if ($.inArray($('#id_Project_Files').val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only formats are allowed : "+fileExtension.join(', '));
            return false;
        }

        $.ajax({
            url:  "{% url 'showlisting'  %}",
            type: "POST",
            data: data,
            cache: false,
            processData: false,
            contentType: false,
            success: function(data) {
                $('#files_data').empty();
                console.log(data[0]['pk']);
                $.map( JSON.parse(data), function( val,index ) {
                    $('#files_data').append('<tr><td>File Name</td><td><a href="">'+val.fields.Project_Files+'</a></td></tr>')
                console.log(val.fields.Project_Files)
                });
            }
        });
        return false;
        });
});
</script>